remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: My Test Blog on Github
description: Test page for a Blog on Github

show_downloads: false

---
---

@import "{{ site.theme }}";
